In [1]:
import numpy as np

In [3]:
#NumPy ufuncs
# ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.




What is Vectorization?


In [4]:
#Converting iterative statements into a vector based operation is called vectorization.



In [7]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]       #  without using ufun 
z = []
for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [8]:
#  using  ufun 

# NumPy has a ufunc for this, called add(x, y) that will produce the same result.

#With ufunc, we can use the add() function:



In [9]:
x = [1,2,3,4,5]
y = [6,7,8,9,10]
z = np.add(x,y)
print(z)

[ 7  9 11 13 15]


# How To Create Your Own ufunc


In [10]:
# The frompyfunc() method takes the following arguments:

#function - the name of the function.
#inputs - the number of input arguments (arrays).
#outputs - the number of output arrays.

In [11]:
# Create your own ufunc for addition:

def myadd (x,y):
  return x+y
  myadd = np.frompyfunc(myadd, 2,1)
  print(myadd([1,2,3,4,5],[6,7,8,9,10]))

In [13]:
print(type(np.add))


<class 'numpy.ufunc'>


In [14]:
if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


# Simple Arithmetic


In [15]:
# Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.



Addition

In [18]:
# The add() function sums the content of two arrays, and return the results in a new array.


In [16]:
import numpy as np

In [19]:
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
newarr = np.add(arr1,arr2)

print(newarr)

[30 32 34 36 38 40]


Subtraction


In [21]:
# The subtract() function subtracts the values from one array with the values from another array,
# and return the results in a new array.



In [22]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newar = np.subtract(arr1,arr2)
print(newar)

[-10  -1   8  17  26  35]


Multiplication


In [23]:
# The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.



In [24]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

new = np.multiply(arr1,arr2)
print(new)

[ 200  420  660  920 1200 1500]


Division

In [26]:
# The divide() function divides the values from one array with the values from another array,
# and return the results in a new array.



In [27]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarray = np.divide(arr1,arr2)
print(newarray)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


Power

In [28]:
#The power() function rises the values from the first array to the power of the values of the second array,
# and return the results in a new array.



In [30]:

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

powr = np.power(arr1,arr2)
print(powr)

[         1000       3200000     729000000 6553600000000          2500
             0]


Remainder


In [31]:
# Both the mod() and the remainder() functions return the remainder of the values in the first array 
#corresponding to the values in the second array, and return the results in a new array.



In [35]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)           #  mod()  and remainder() are same'
print(newarr)

[ 1  6  3  0  0 27]


In [36]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


Quotient and Mod


In [37]:
#  The divmod() function return both the quotient and the the mod. The return value is two arrays,
# the first array contains the quotient and second array contains the mod.



In [38]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

new = np.divmod(arr1,arr2)
print(new)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


Absolute Values


In [39]:
# Both the absolute() and the abs() functions functions do the same absolute operation element-wise but 
# we should use absolute() to avoid confusion with python's inbuilt math.abs()



In [40]:
arr = np.array([-1, -2, 1, 2, 3, -4])

new = np.absolute(arr)
print(new)

[1 2 1 2 3 4]


# Rounding Decimals


In [ ]:
# There are primarily five ways of rounding off decimals in NumPy:
"""
truncation
fix
rounding
floor
ceil
"""

Truncation

In [41]:
# Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.



In [44]:
# Truncate elements of following array:

arr = np.trunc([-3.1666, 3.6667])
new = np.trunc(arr)                        #  trunc() and fix() doing same work
print(arr)

[-3.  3.]


In [45]:
# Same example, using fix():

arr = np.trunc([-3.1666, 3.6667])
new = np.fix(arr)
print(new)

[-3.  3.]


Rounding


In [46]:
# The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

# E.g. round off to 1 decimal point, 3.16666 is 3.2

In [47]:
arr = np.around(3.1666, 2)

print(arr)

3.17


Floor


In [48]:
# The floor() function rounds off decimal to nearest lower integer.

# E.g. floor of 3.166 is 3.

In [49]:
arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


Ceil

In [50]:
# The ceil() function rounds off decimal to nearest upper integer.

# E.g. ceil of 3.166 is 4.

In [51]:
arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


# NumPy Summations


Summations


In [52]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


In [54]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


Summation Over an Axis


In [55]:
# If you specify axis=1, NumPy will sum the numbers in each array.



In [56]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)     # axis= 1

print(newarr)

[6 6]


In [58]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=0)    #  axis = 0

print(newarr)

[2 4 6]


Cummulative Sum


In [59]:
# Cummulative sum means partially adding the elements in array.

# E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

# Perfom partial sum with the cumsum() function.

In [61]:
arr = np.array([1, 2, 3])

new = np.cumsum(arr)
print(new)

[1 3 6]
