In [1]:
import numpy as np

In [2]:
# Joining means putting contents of two or more arrays in a single array.



In [3]:
#   Join two arrays



In [4]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [6]:
arr = np.concatenate((arr1,arr2))

In [7]:
print(arr)

[1 2 3 4 5 6]


# Join two 2-D arrays along rows (axis=1):



In [12]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
print(arr1,arr2)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [9]:
arr = np.concatenate((arr1,arr2), axis = 1)     #  Column wise joining

In [10]:
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [13]:
ar = np.concatenate((arr1,arr2))                 #  rows wise joinig
print(ar)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Joining Arrays Using Stack Functions


In [14]:
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.



In [15]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
ar = np.concatenate((arr1,arr2))
print(ar)

[1 2 3 4 5 6]


In [22]:
ar = np.stack((arr1,arr2))

In [23]:
print(ar)

[[1 2 3]
 [4 5 6]]


# Stacking Along Rows


In [24]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])                 # rows wise
arr = np.hstack((arr1, arr2))              # Using hstack function

print(arr)

[1 2 3 4 5 6]


# Stacking Along Columns


In [26]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])           # column wise

arr = np.vstack((arr1, arr2))       # Using vstack function

print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Height (depth)


In [27]:
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.



In [29]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))     # uaing dstack function

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array


In [31]:
# Splitting is reverse operation of Joining.

# Joining merges multiple arrays into one and Splitting breaks one array into multiple.

# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])


In [33]:
newar = np.array_split(arr,3)

In [34]:
print(newar)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [40]:
ar = np.array_split(arr,2)
print(ar)

[array([1, 2, 3]), array([4, 5, 6])]


In [41]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)       # there are not proper elements but split properly

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


Split Into Arrays


In [42]:
# he return value of the array_split() method is an array containing each of the split as an array.

# If you split an array into 3 arrays, you can access them from the result just like any array element:

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
print(newar)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [46]:
print(newar[0])
print(newar[1])
print(newar[2])

[1 2]
[3 4]
[5 6]


Splitting 2-D Arrays


In [47]:
# Split the 2-D array into three 2-D arrays.



In [53]:

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(arr.ndim)

newarr = np.array_split(arr, 3)

print(newarr)

2
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [56]:
print(newarr[2])


[[ 9 10]
 [11 12]]


In [57]:
# Split the 2-D array into three 2-D arrays along rows.



In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [59]:
print(newarr[2])

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [60]:
# An alternate solution is using hsplit() opposite of hstack()



In [61]:

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays


In [62]:
# To search an array, use the where() method.



In [63]:
# Find the indexes where the value is 4:

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [64]:
# Find the indexes where the values are even:



In [66]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)          #  output in indexing wise

(array([1, 3, 5, 7]),)


# Search Sorted


In [67]:
# The searchsorted() method is assumed to be used on sorted arrays.



In [72]:
# Find the indexes where the value 7 should be inserted:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)                           # we can find of indexing of element

1


Search From the Right Side


In [73]:
# Find the indexes where the value 7 should be inserted, starting from the right:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [74]:
# Find the indexes where the values 2, 4, and 6 should be inserted:

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# NumPy Sorting Arrays


In [75]:
# Sorting means putting elements in an ordered sequence.

# The NumPy ndarray object has a function called sort(), that will sort a specified array.



In [76]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [77]:
# Sort the array alphabetically:

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [78]:
# Sort a boolean array:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Sorting a 2-D Array


In [79]:
# If you use the sort() method on a 2-D array, both arrays will be sorted:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy Filter Array


In [80]:
# Getting some elements out of an existing array and creating a new array out of them is called filtering.

# In NumPy, you filter an array using a boolean index list.

# A boolean index list is a list of booleans corresponding to indexes in the array.

In [81]:
# If the value at an index is True that element is contained in the filtered array, 
# if the value at that index is False that element is excluded from the filtered array.



In [83]:
# Create an array from the elements on index 0 and 2:

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)  #  the filter array had the value True, in this case, index 0 and 2.



[41 43]


Creating the Filter Array


In [84]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [85]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array


In [86]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [87]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
