In [1]:
import numpy as np

Products


In [2]:
# To find the product of the elements in an array, use the prod() function.



In [3]:
arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

24


In [4]:
ar = np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
y = np.prod(ar)
print(y)

362880


In [6]:
n = np.sum(arr)

In [7]:
print(n)

10


In [8]:
# Find the product of the elements of two arrays:



In [9]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])


In [11]:
newarr= np.prod([arr1,arr2])
print(newarr)

40320


Product Over an Axis


In [12]:
# If you specify axis=1, NumPy will return the product of each array.



In [13]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

In [14]:
new = np.prod([arr1, arr2], axis=1)   #  rows wise prod()
print(new)

[  24 1680]


In [16]:
newcol= np.prod([arr1,arr2],axis= 0)  #   column wise prod()
print(newcol)

[ 5 12 21 32]


# NumPy Differences


In [17]:
# Differences
# A discrete difference means subtracting two successive elements.

# E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

# To find the discrete difference, use the diff() function.

In [18]:
arr = np.array([10, 15, 25, 5])

x = np.diff(arr)
print(x)

[  5  10 -20]


In [19]:
# Compute discrete difference of the following array twice:

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)
print(newarr)


[  5 -30]


# NumPy LCM

In [20]:
# The Lowest Common Multiple is the least number that is common multiple of both of the numbers.



In [21]:
num1 = 4
num2 = 6

new = np.lcm(num1,num2)
print(new)

12


Finding LCM in Arrays


In [22]:
# To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.



In [23]:
arr = np.array([3, 6, 9])

new= np.lcm.reduce(arr)
print(new)

18


In [24]:
# Find the LCM of all of an array where the array contains all integers from 1 to 10:

arr = np.arange(1, 11)
new= np.lcm.reduce(arr)
print(new)


2520


# NumPy GCD Greatest Common Denominator


In [25]:
# The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is
#  the biggest number that is a common factor of both of the numbers.



In [26]:
num1 = 6
num2 = 9
new = np.gcd(num1,num2)
print(new)

3



Finding GCD in Arrays


In [27]:
# The reduce() method will use the ufunc, in this case the gcd() function, on each element,
#  and reduce the array by one dimension.



In [28]:
arr = np.array([20, 8, 32, 36, 16])
new = np.gcd.reduce(arr)

In [29]:
print(new)

4


# NumPy Set Operations


In [30]:
# A set in mathematics is a collection of unique elements.

# We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array,
# but remember that the set arrays should only be 1-D arrays.



In [31]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])


In [32]:
new = np.unique(arr)
print(new)

[1 2 3 4 5 6 7]


Finding Union


In [33]:
# To find the unique values of two arrays, use the union1d() method.



In [34]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

In [35]:
new = np.union1d(arr1, arr2)

print(new)

[1 2 3 4 5 6]


Finding Intersection


In [36]:
# To find only the values that are present in both arrays, use the intersect1d() method.



In [37]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])


In [38]:
newarr = np.intersect1d(arr1,arr2, assume_unique=True)

In [39]:
print(newarr)

[3 4]


Finding Difference


In [40]:
# To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.



In [41]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

In [42]:
newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

[1 2]
