In [3]:
import numpy as np
# Creating NumPy Arrays

arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


# From built-in methods

In [4]:
arr2 = np.zeros((2, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr3 = np.ones((3, 2))
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
arr4 = np.arange(0, 10, 2)
arr4

array([0, 2, 4, 6, 8])

In [7]:
arr5 = np.linspace(0, 1, 5)
arr5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# From random

In [8]:
arr6 = np.random.rand(2, 2)
arr6

array([[0.97619103, 0.98696333],
       [0.22943216, 0.94935423]])

In [9]:
arr7 = np.random.randint(1, 10, size=(3, 3))
arr7

array([[2, 8, 7],
       [7, 6, 4],
       [2, 7, 6]])

# Array Attributes and Methods


In [10]:
arr7

array([[2, 8, 7],
       [7, 6, 4],
       [2, 7, 6]])

In [11]:
print("Shape:", arr7.shape)


Shape: (3, 3)


In [12]:
print("Data type:", arr7.dtype)


Data type: int32


In [13]:
print("Size:", arr7.size)


Size: 9


In [14]:
print("Dimensions:", arr7.ndim)


Dimensions: 2


In [15]:
print("Max:", arr7.max())


Max: 8


In [16]:
print("Min:", arr7.min())


Min: 2


In [17]:
print("Argmax:", arr7.argmax())


Argmax: 1


In [18]:
print("Argmin:", arr7.argmin())


Argmin: 0


In [19]:
reshaped = arr7.reshape(1, 9)
print("Reshaped:\n", reshaped)

Reshaped:
 [[2 8 7 7 6 4 2 7 6]]


# Operations on Arrays


In [20]:
arr7

array([[2, 8, 7],
       [7, 6, 4],
       [2, 7, 6]])

In [21]:
arr_copy = arr7.copy()
arr_copy

array([[2, 8, 7],
       [7, 6, 4],
       [2, 7, 6]])

In [22]:
appended = np.append(arr1, [5, 6])
appended

array([1, 2, 3, 4, 5, 6])

In [23]:
inserted = np.insert(arr1, 1, 99)
inserted

array([ 1, 99,  2,  3,  4])

In [24]:
sorted_arr = np.sort(arr7, axis=1)
sorted_arr

array([[2, 7, 8],
       [4, 6, 7],
       [2, 6, 7]])

In [25]:
deleted = np.delete(arr1, [1, 2])
deleted

array([1, 4])

In [26]:
combined = np.concatenate((arr1, appended))
combined

array([1, 2, 3, 4, 1, 2, 3, 4, 5, 6])

In [29]:
split = np.split(arr1, 2)
split

[array([1, 2]), array([3, 4])]

In [30]:
# Data Loading & Saving
np.save('array_file.npy', arr7)
loaded_arr = np.load('array_file.npy')
loaded_arr

array([[2, 8, 7],
       [7, 6, 4],
       [2, 7, 6]])

In [31]:
# NumPy Indexing and Selection
matrix = np.array([[10, 20, 30],
                   [40, 50, 60]])

print("Element at (1,1):", matrix[1, 1])
print("First row:", matrix[0])
print("Logical Selection:", matrix[matrix > 30])

Element at (1,1): 50
First row: [10 20 30]
Logical Selection: [40 50 60]


In [32]:
matrix

array([[10, 20, 30],
       [40, 50, 60]])

In [34]:
# Broadcasting and Type Casting
broadcasted = matrix + 100
print(broadcasted)
print("")
casted = matrix.astype(float)
print(casted)

[[110 120 130]
 [140 150 160]]

[[10. 20. 30.]
 [40. 50. 60.]]


# Arithmetic Operations


In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Add:", a + b)

Add: [5 7 9]


In [36]:
print("Subtract:", a - b)


Subtract: [-3 -3 -3]


In [37]:
print("Multiply:", a * b)


Multiply: [ 4 10 18]


In [38]:
print("Divide:", a / b)


Divide: [0.25 0.4  0.5 ]


In [39]:

print("Exponentiation:", a ** 2)

Exponentiation: [1 4 9]


# Universal Array Functions


In [45]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a,b)

[1 2 3] [4 5 6]


In [42]:
print("Square Root:", np.sqrt(a))


Square Root: [1.         1.41421356 1.73205081]


In [43]:
print("Exponential:", np.exp(a))


Exponential: [ 2.71828183  7.3890561  20.08553692]


In [44]:
print("Maximum:", np.maximum(a, b))

Maximum: [4 5 6]
