In [51]:
import numpy as np

Random Numbers in NumPy


In [52]:
from numpy import random


In [53]:
x = random.randint(100)


In [54]:
print(x)

63


In [55]:
v = random.randn(10)

In [56]:
print(v)

[-0.60830029 -1.48241641  0.18716604 -0.25219607  1.64588331 -0.176249
  0.31020548 -2.20548238 -1.49544864  0.18484484]


In [57]:
x = random.rand()


In [58]:
print(x)

0.5231256481978788


In [59]:
arr = random.rand()
print(arr)

0.2661940825592142


In [60]:
arr = random.randn()
print(arr)

0.2290512134528824


In [61]:
arr= random.rand(10)
print(arr)

[0.41559004 0.98017635 0.61129678 0.86409257 0.02573649 0.17604998
 0.08298193 0.40807769 0.38021513 0.25240408]


In [62]:
arr = random.randn(10)
print(arr)

[-0.64256146 -2.42689402 -1.672218   -0.67776593 -0.39190458  0.1486327
  0.79766454  0.2948207   0.5983486  -1.03320503]


Generate Random Array


In [63]:
x = random.randint(100,size=5)

In [64]:
print(x)

[71 76 25 66 65]


In [65]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:



In [66]:
x = random.randint(100, size=(3,5))

In [67]:
print(x)

[[82 18 15 97 14]
 [10 70 89 81 29]
 [61 76 58  8 74]]


The rand() method also allows you to specify the shape of the array.



In [68]:
x = random.rand(5)
x

array([0.50312943, 0.61731995, 0.769376  , 0.82510612, 0.38395549])

In [69]:
x = random.rand(3, 5)
print(x)

[[0.6243214  0.32450356 0.26791542 0.59450038 0.70565219]
 [0.58234773 0.1297245  0.78894329 0.90289269 0.85671837]
 [0.10230652 0.51157691 0.41430743 0.16822699 0.97681826]]


#Shuffling Arrays


In [70]:
# Randomly shuffle elements of following array:

arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[5 4 3 1 2]


In [71]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))


[5 4 3 1 2]


In [72]:
arr = random.randint(1000, size=(4,5))

In [73]:
print(arr)

[[109 454 554 948 651]
 [804 779 160 436 111]
 [272 443 450 512 554]
 [713 689 590 324 389]]


In [74]:
random.shuffle(arr)

In [75]:
print(arr)

[[109 454 554 948 651]
 [272 443 450 512 554]
 [713 689 590 324 389]
 [804 779 160 436 111]]


In [76]:
random.shuffle(arr)
print(arr)

[[804 779 160 436 111]
 [272 443 450 512 554]
 [713 689 590 324 389]
 [109 454 554 948 651]]
